package com.example.wazitoecommerce.models

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn

class MainViewModel : ViewModel() {
    //first state whether the search is happening or not
    private val _isSearching = MutableStateFlow(false)
    val isSearching = _isSearching.asStateFlow()

    //second state the text typed by the user
    private val _searchText = MutableStateFlow("")
    val searchText = _searchText.asStateFlow()

    //third state the list to be filtered
    private val _countriesList = MutableStateFlow(countries)
    val countriesList = searchText
        .combine(_countriesList) { text, countries ->//combine searchText with _contriesList
            if (text.isBlank()) { //return the entery list of countries if not is typed
                countries
            }
            countries.filter { country ->// filter and return a list of countries based on the text the user typed
                country.uppercase().contains(text.trim().uppercase())
            }
        }.stateIn(//basically convert the Flow returned from combine operator to StateFlow
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),//it will allow the StateFlow survive 5 seconds before it been canceled
            initialValue = _countriesList.value
        )

    fun onSearchTextChange(text: String) {
        _searchText.value = text
    }

    fun onToogleSearch() {
        _isSearching.value = !_isSearching.value
        if (!_isSearching.value) {
            onSearchTextChange("")
        }
    }

}

private val countries = listOf(


   " The Cat Hospital",
   "The Vet Spectrum",
   " Pet’s Best Vet Clinic",
    "Harmony for Animals",
    "Refuge Village Veterinary",
    "Scottsdale Vets",
    "Vet Groom",
    "Well Pets",
    "Veterinary Care",
    "The Cat & Paw Clinic",

    "FastMed Urgent Care",
    "BestCare Animal Hospital",
    "Rural Vets",
    "Just  Cats",
    "Trusty Pets",
    "Animal Veterinary Clinic",
    "Priority Pet Clinic",
    "GoodVets Uptown",
    "Refuge Pets Animal Hospital",
    "Caribou Rental Vet",
    "Camelback Vets",
    "Vet Specialty & Surgical Services",
    "All Kinds of Heros",
    "Happy Horse Hospital",
    "ArchPaw Veterinary & Animal Hospital",
    "Aspiring Veterinary Services",
    "The DVM Office	Care Vet",
    "Hill Country Veterinary Hospital",
    "Veterinary Edge",
    "DrPawPaw	VCA Animal Clinic",
    "AZ Animal Resort",
    "Friendly Animal Hospital",
    "Washburn Equine",
    "All about Puppy Care",
    "Creature Comforts Clinic and Surgical Center",
    "K9 Pooch Service",
    "Lincoln Ridge Dental",
    "Healthy Paws Animal Veterinary Clinic",
    "Integrity Animal Care",
    "Goodwill Vet Clinic",
    "Fauna Animal Care & Therapy",
    "Cahill Animal Hospital",
    "Sunbury Veterinary Clinic",
    "Healthy Standard Of Care Animal Hospital",
    "1 Pet Resort",
    "Very Good Veterinarians",
    "Neona Arch Animal Hospital",
    "Animales Animales",
    "Crystal Mountain Animal Hospital",
    "Pet Life Animal Hospital	Clinicats",
    "Banfield Pet Hospital",
    "The Heel Animal Hospital",
    "AllPet Healing",
    "Vet Med Services",
    "Paw Passion Your Pets Animal Clinic",
    "Lucky White Vet",
    "All Pet Vet Services",
    "DoctorBliss",
    "Charlie’s Pet Care",
    "Homewatch EAS	CutePaw",
    "Total Pet Health",
    "Austin Vet Care",
    "Wild West Vet",
    "Lil Pet Animal Clinic",
    "Sciulli Svetronika",
    "Globetrotter Animal Hospital",
    "Amity Animal Hospital",
    "Vetcall Animal Hospital",
    "Feline Frenzy	Wide Valley	Pet Clinic of Tempe",
    "National Veterinary Care",
    "Mo West	Heal Veterinary Clinic",
    "A Plus Plus Vet",
    "Orion Animal Clinic",
    "After Hours Vet Clinic",
    "Empower Cat Clinic",
    "Even Port Animal Hospital",
    "Cruisin’ Pets Hospital",
    "The Pet Doctors",
    "Amelyn Animal Hospital",
    "Best in Show Vets",
    "Pray It With Love",
    "Stanford Animal Clinic",
    "Crazy Cat Clinic",
    "Exceptional Vets ",
    "Greaton Animal Hospital",
    "The AnimalCures",
    "Pawn1st Dog Clinic	Wide Way",
    "Bella Wild Rabbit",
    "Horse’s Kingdom Vet",
    "Happy Pets Animal Hospital",
    "Furever Vets",
    "A Friendly Vet	Pet Panorama",
    "Dogwood Animal Clinic",
    "Animates Vetcare Clinic",
    "Sandberg Animal Hospital",
    "Small Animal Veterinary Centre",
    "Trusty Pet Hospital",
    "Health fest",
    "Escape Vet",
    "Vet Cat Clinic",
    "Victor Wood	Mobile Veterinary Clinic",
    "MedVet	Pet Nest Animal Hospital",
    "Prime Days Pets",
    "Urban Pet Healthcare",
    "Animal Bliss Animal Clinic",
    "Recovery Pet Clinic",
    "Petfectionn	Treat Hope",
    "Health4Life Veterinarians",
    "Good Cat Practice",
    "Lorenzo Animal Hospital",
    "White Rock Veterinary",
    "Diva Dental Care",
    "West Berg Animal Clinic",
    "West Loop Veterinary Care",
    "Animal Smile Vet",
    "Elite East Animal Hospital",
    "Crestview Veterinary Clinic",
    "Athena’s Paws Clinic",
    "Rosewood Vets",
    "Dog Priority Clinic",
    "Feline Care Clinic",
    "Pet Metz Animal Hospital",
    "Moving Forward Veterinarians",
    "Cats Love Housecalls",
    "Health Hill	Piper Street Vet Clinic",
    "Northlands Animal Care Hospital",
    "Zing Crest	Vet’s Choice Pals",
    "North Shore Veterinary Clinic",
    "Animal Help",
    "Sunset Veterinary Clinic",
    "The Pet Uclick",
    "Pet Space Animal Hospital",
    "Bird Vet Clinic",
    "Lovestock and Home	Wills Berry	Royal Crest Vet Clinic",
    "Seeming Veterinary Clinic",
    "New life Animal Hospital	Veterinareurs",
    "ApexpetCare",
    "Planet Pets",
    "Totally Vets",
    "Pet-tastic Care",
    "Sky Pets Animal Hospital",
    "Treatment Pet Clinic",
    "Happy Paws	Crazy Pans",
    "Firehouse Animal Health Center",
    "Paws and Claws Veterinary Clinic",
    "Coastal Bay Animal Clinic",
    "Animal Emergency & Referral Centre",
    "PAWS Medical Center",
    "Pet Essen Animal Hospital",
    "Victoria Veterinary center",
    "Pet Animal Hospitals",
    "White Wave Animal Clinic",
    "Healthy Bones Clinic",
    "Animal Welfare	",
    "Safe Crew Animal Hospital",
    "Vets North",
    "Cat Care Clinic",
    "Happy Grid Animal Clinic",
    "Hospitalizing Cats",
    "Animal and Bird Hospital",
    "Health Quest Animal Clinic",
    "A Cat’s All That",
    "Elite Vet",
    "Puppy Comfy Animal Clinic",
    "Veterinary Partners",
    "Morning Veterinary Centre",
    "New Crest Animal Hospital",
    "Vet Around Town",
    "Beautiful Pets Boutique",
    "Animal Curves Animal Clinic",
    "Happy Paws Veterinarians",
    "Heritage Veterinary Clinic",
    "Healing Shades	First Vets",
    "Andy’s Veterinary Clinic",
    "Wood Wings Animal Hospital",
    "Animal Center Vet",
    "Street Veterinary Clinic",
    "Aeroben Pups",
    "Animal Emergency & Treatment Centers",
    "The PawProtectors",
    "Heal Motto	Small Animal Clinic",
    "Paw Priority",
    "Saving Hands Animal Hospital",
    "Caspian Vet",
    "Republic Veterinary Hospital",
    "Spring Berg	Veterinary",
    "Vet Farm & Pet Clinic",
    "Star Eager Animal Clinic",
    "GoodVets West Loop",
    "Peterinarians	Health Track",
    "Pet Health Centre",
    "Cowell Veterinary Clinic",
    "Trinity Animal Clinic",
    "The Pet Priority",
    "Pets First	Cosmix Animal Hospital",
    "Pear Pet Vaccines",
    "The WellPets",
    "Healo fly Animal Clinic",
    "My Pet Clinic",
    "A+ Cattery	Wynk Way Animal Clinic",
    "Newtown Pet Clinic",
    "The Pet Practice",
    "Pet Circle Animal Hospital",
    "Goal Vet Clinic",
    "Las Vegas Wild Vet",
    "Med fix Animal Hospital",
    "A Cat’s Life",
    "Bat City Mobile Vet Care",
    "White Safe Animal Clinic",
    "Dogs & Cats First",
    "Holistic Vets",
    "Happy Graphy",
    "Wild Companion Vet",
    "Vets One",
    "Heal Master Animal Hospital",
    "Goodland Veterinary Clinic",
    "Road Vet Clinic",
    "Pet Quest Animal Clinic",
    "Vet For Your Pets",
    "Capital Veterinary Clinic",
    "Pet Presto Animal Hospital	CritterAide",
    "Paradise Valley Vet",
    "Prime Stone",
    "VetCare Finance",
    "Feel Healed Vets",
    "Urban Pets",
    "Horse’s Haven Vet Clinic",
    "Preventive Vet",
    "Marvello Animal Hospital",
    "Animated Animal Doctors",
    "Vets4Pets",
    "Austin Animal Hospital",
    "Pathway Vet Alliance",
    "The Cat Clinic",
    "Fusion Paws",
    "Vetlife Twizel",
    "Victory Vets",
    "Peto Flex Animal Clinic",
    "Whistler Veterinary",
    "A & B Pet Care",
    "Alright Animal Hospital",
    "Peak’s Animal Clinic",
    "Your friendly vet",
    "Well Ware	Wild Pet Desert",
    "Louisville Vet",
    "North Bay Animal Clinic",
    "Cattle And Bull",
    "C & A Veterinarian",
    "Healo Right",
    "Memorial Avenue Vet Clinic",
    "Rosedale Veterinary Clinic",
    "Aroma Animal Hospital",
    "Humanimals Trusted Vets",
    "Stepex Animal Clinic",
    "Animals for Animals",
    "D&E Veterinary",
    "Servo Sense	Pet Place",
    "Pet Health Group" ,
    "Pet Trail Animal Hospital",
    "Hank’s Pet Clinic",
    "Bee Cave Veterinary Clinic",
    "Vet About Town",
    "Vetuoso	Sawyer’s Vet Clinic",
    "Fix It Veterinary Clinic",
    "Acute Companion Veterinary Clinic",
    "Animal First Clinic",
    "Greenway Street Vet",
    "Companion Care Clinic",
    "Mayfair Animal Clinic",
    "Vet-It up Clinic",
    "Fine Vision Vet Clinic",
    "Cool Creatures	",
    "Flying High Veterinarian",
    "slice a mice",
    "Magic Paws	Animaleon",
   "Comfortreatment Pet Clinic",
    "Pawing Packs",
    "Love Pet Hospital",
    "Gerbil Town	Animal House",
    "Feline Fetch",
    "Fauna Vet Clinic",
    "Creature Comforts",
    "Oliver Animal Hospital",
    "DoctorWell	Giga Pet Clinic",
    "Petcare Vet Clinic",
    "Gratus Animal Hospital",
    "Puppy Love	Handy Veterinary Clinic & Hospital",
    "Profound Vet Services",
    "Pet Life Care",
    "Delta Animal Hospital",
    "The Total Pet",
    "Comfort Treatment",
    "Meline’s Home",
)